baseURL = 'https://ethd.foxx.ink/'
title = 'Hugo ET-HD'
theme = 'hugo-et-hd'
lastmod = ["lastmod", ":fileModTime", ":default"]
canonifyURLs = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[params]
	description = 'Hugo ET-HD exampleSite'
	# DisableBypassBlock = false    # disable bypass block (jump to article/jump to top), for accessibility purpose please keep this setting enable
	# WebSafeFonts = true   # use websafe fonts
	localfonts = true   # if fonts hosted on localhost (static/css/fonts)
	OptInSocialMeta = true    # add meta data for opengraph and twitter

	[params.post]
		justify = false   # justified paragraph
		noIndent = false    # remove paragraph indent
		authorcard = false   # only show if site author equal with post author

	[params.home]
		slider = true   # disable landing page slider, only first page of feed
		layoutSplit = false    # landing page slider dependent, dual panel style landing page
		# banner = '<img src="" />'   # use custom landing page banner, use safeHTML
		# bannercentering = true    # centering landing page banner
		# authorCard = true    # show site author cards on landing page

	[params.feed]
		summary = true   # display summary
		grid = true    # feed display grid
		cover = true    # display post cover
		FlowlinesLimit = 21   # max=42, limit random flow lines used for post cover
		headline = true    # headline latest post

	[params.author]
		name = 'John Doe'
		bio = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
		# email = 'johndoe@example.com'
		# avatar = ''    # url, used for author card

	[params.initial] # override legibility controls onload
		# FontScale = 1
		# BaselineStretch = 1
		# ForceOpenDyslexic = false
		# scheme = 'dark' # 'dark' | 'light'
		# contrast = 'high'# 'low' | 'less' | 'more' | 'high'

[markup]

	[markup.highlight]
		codeFences = true
		hl_Lines = ""
		lineNoStart = 1
		lineNos = true
		lineNumbersInTable = true
		noClasses = false
		tabWidth = 4

  	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		[markup.goldmark.extensions]
			[markup.goldmark.extensions.passthrough]
				enable = true
			[markup.goldmark.extensions.passthrough.delimiters]
				block = [['\[', '\]'], ['$$', '$$']]
				inline = [['\(', '\)'], ['$', '$']]

[languages]
	[languages.en]
		contentDir = 'content/en'
		disabled = false
		languageCode = 'en-US'
		languageDirection = 'ltr'
		languageName = 'English'
		# title = 'Hugo ET-HD'
		weight = 1
		[languages.en.params]
			footnote = '<i>John &copy; 2024</i>'

		[languages.en.params.home]
			tagline = 'Just another exampleSite'

	[[languages.en.menu.main]]
		pre = 'ethd'
		name = 'Home'
		identifier = 'ethd'
		weight = 1
		title = 'Home' # please set if name not defined
		[[languages.en.menu.main.params]]
			isBanner = true # please set the banner once

	[[languages.en.menu.main]]
		identifier = 'archive'
		pre = 'archive'
		name = 'archive'
		url = '/en/post/'
		weight = 2
		[[languages.en.menu.main.params]]
			pos = 'lfill' # Positional control class: < lfill | hfill | rfill >

	# [[languages.en.menu.main]]
	# 	identifier = 'fork'
	# 	pre = 'git'
	# 	name = 'fork'
	# 	url = 'https://github.com/foxihd/hugo-et-hd/'
	# 	weight = 3

	# [[languages.en.menu.social]]
	# 	identifier = 'Figma'
	# 	pre = 'figma'
	# 	url = '#uh-oh'
	# 	weight = 1
	# 	title = 'Figma'
	# [[languages.en.menu.social]]
	# 	identifier = 'Hashnode'
	# 	pre = 'hashnode'
	# 	url = '#uh-oh'
	# 	weight = 2
	# 	title = 'Hashnode'
	[[languages.en.menu.social]]
		identifier = 'Email'
		pre = 'email'
		url = '#uh-oh'
		weight = 3
		title = 'E-mail'
	[[languages.en.menu.social]]
		identifier = 'Linkedin'
		pre = 'linkedin'
		url = '#uh-oh'
		weight = 4
		title = 'Linkedin'
	# [[languages.en.menu.social]]
	# 	identifier = 'Karyakarsa'
	# 	pre = 'karyakarsa'
	# 	url = '#uh-oh'
	# 	weight = 5
	# 	title = 'Karyakarsa'

	# [[languages.en.menu.other]]
	# 	identifier = 'demo1'
	# 	name = 'Demo'
	# 	pre = 'store'
	# 	url = '#uh-oh'
	# 	title = 'Demo'
	# [[languages.en.menu.other]]
	# 	identifier = 'demo3'
	# 	name = 'Demo'
	# 	pre = 'orcid'
	# 	url = '#uh-oh'
	# 	title = 'Demo'
	# [[languages.en.menu.other]]
	# 	identifier = 'demo2'
	# 	name = 'Demo'
	# 	pre = 'buymeacoffee'
	# 	url = '#uh-oh'
	# 	title = 'Demo'

	# [[languages.en.menu.foot]]
		# identifier = 'id'
		# pre = 'www'
		# name = 'ID'
		# url = '/id'
		# title = 'Beralih ke Bahasa Indonesia'
		# [[languages.en.menu.foot.params]]
		# 	class = 'ssc sf'